### ISSUE TITLE
EasyBuild crashed with an error: Requested toolchain name goalf not available, only dummy

### ISSUE THREAD

**Issue by malcook** [hpcugent/easybuild-framework#1147]
Hi,

I find two issues running easybuild bootstrap method following http://easybuild.readthedocs.org/en/latest/Installation.html#bootstrapping-procedure.  

The first I have a workaround for, the second not yet and would appreciate guidance.

 - undocumented: apparently bootstrapeb.py requires `module load lmod` 
 - EasyBuild crashed with an error: Requested toolchain name goalf not available, only dummy

Some details:

After a fresh install of Lua and Lmod on fresh CentOS7 VM....

I source my new  Lmod bash profile, as
```
$ . /n/local/ml/root/lmod/lmod/init/profile
```
I get error 
```
$ curl -O https://raw.githubusercontent.com/hpcugent/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py
$ python bootstrap_eb.py  ${MODULEPATH_ROOT}/easybuild
[[ERROR]] Could not find any module command, make sure one available in your $PATH.
Known module commands are checked in order, and include: modulecmd, lmod, modulecmd.tcl
Check the output of 'type module' to determine the location of the module command you are using.
```
Guessing, I find a workaround that loading the lmod module first gets me further:
```
$ module load lmod
$ python bootstrap_eb.py  ${MODULEPATH_ROOT}/easybuild
[[INFO]] Found module command 'lmod' (Lmod), so using it.
[[INFO]] 

+++ STAGE 0: installing distribute via included (patched) distribute_setup.py...


Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.34.tar.gz
Extracting in /tmp/tmpV5UBLy
Now working in /tmp/tmpV5UBLy/distribute-0.6.34
Installing Distribute
[[INFO]] 

+++ STAGE 1: installing EasyBuild in temporary dir with easy_install...


Installing with setuptools.setup...
Installing version 1.16.1
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

zip_safe flag not set; analyzing archive contents...
Installing with setuptools.setup...
Installing version 1.16.1 (API version 1)
Installing with setuptools.setup...
Installing version 1.16.1 (required versions: API >= 1)
Installing with setuptools.setup...
Installing version 1.16.1.0 (required versions: API >= 1, easyblocks >= 1.16)
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

[[INFO]] 

+++ STAGE 2: installing EasyBuild in /n/local/ml/root/modulefiles/easybuild with EasyBuild from stage 1...


== temporary log file in case of crash /tmp/easybuild-1W_10x/easybuild-nSR_bk.log
Traceback (most recent call last):
  File "bootstrap_eb.py", line 584, in <module>
    main()
  File "bootstrap_eb.py", line 411, in main
    stage2(tmpdir, versions, install_path)
  File "bootstrap_eb.py", line 360, in stage2
    easybuild_main()
  File "/tmp/tmpBfwh1W/eb_stage1/lib/python2.7/site-packages/easybuild_framework-1.16.1-py2.7.egg/easybuild/main.py", line 251, in main
    easyconfigs, generated_ecs = parse_easyconfigs(paths)
  File "/tmp/tmpBfwh1W/eb_stage1/lib/python2.7/site-packages/easybuild_framework-1.16.1-py2.7.egg/easybuild/framework/easyconfig/tools.py", line 315, in parse_easyconfigs
    ecs = process_easyconfig(ec_file, **kwargs)
  File "/tmp/tmpBfwh1W/eb_stage1/lib/python2.7/site-packages/easybuild_framework-1.16.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 937, in process_easyconfig
    _log.exception(msg)
  File "/tmp/tmpBfwh1W/eb_stage1/lib/python2.7/site-packages/easybuild_framework-1.16.1-py2.7.egg/easybuild/tools/build_log.py", line 120, in exception
    raise EasyBuildError(newMsg)
easybuild.tools.build_log.EasyBuildError: 'EasyBuild encountered an exception (at easybuild/framework/easyconfig/easyconfig.py:937 in process_easyconfig): Failed to process easyconfig /tmp/tmpBfwh1W/EasyBuild-1.16.1.eb:\nEasyBuild crashed with an error (at easybuild/framework/easyconfig/format/one.py:79 in get_config_dict): Requested toolchain name goalf not available, only dummy'
```

Below are results of [requested](http://easybuild.readthedocs.org/en/latest/Installation.html#in-case-of-installation-issues) diagnostics:

```
 python -V
Python 2.7.5
$ type -f module
bash: type: module: not found
$ module --version

Modules based on Lua: Version 5.8.4 (5.8.4-1-g5f35f0f) 2015-01-23 13:24
    by Robert McLay mclay@tacc.utexas.edu

$ module av EasyBuild
sh: /n/local/ml/root/lmod/lmod/libexec: Is a directory
$ which -a eb
/usr/bin/which: no eb in (/n/local/ml/root/lmod/lmod/libexec:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin)
$ : #$ eb --version
bash: eb: command not found
```

**Comment by boegel** [comment]
Hi @malcook, thank you for reporting the issues you've run into!

The first problem, that you solved by loading the `lmod` module, occurs because EasyBuild requires that the `lmod` binary is available via `$PATH` (as the error message you run into states).

This is indeed not clear in the documentation at http://easybuild.readthedocs.org/en/latest/Installation.html, I'll look into fixing that.

The second issue you're running into is *very* weird, giving the error message you run into: `Requested toolchain name goalf not available, only dummy`.

Can you try running the bootstrap script in debug mode, by setting `print_debug` to `True` on line 53 of `bootstrap_eb.py` after you've downloaded it?

This will produce very verbose output, so maybe run the bootstrap like this to capture all output to a file:

```
python bootstrap_eb.py  ${MODULEPATH_ROOT}/easybuild 2>&1 | tee bootstrap_eb.log
```

And then provide `bootstrap_eb.log` to us, e.g. via a gist (http://gist.github.com).

It seems like your Lmod installation also doesn't fully work yet, maybe because `$LMOD_CMD` is not set. Try something like `export LMOD_CMD=/n/local/ml/root/lmod/5.8.4/libexec` before using the `module` command.

Also: you should update to Lmod 5.8.5, since some issues w.r.t. the packaging of the 5.8.4 were uncovered.

**Comment by boegel** [comment]
@malcook: updated the docs w.r.t. requiring `lmod` to be available in `$PATH`

Let me know if you can provide a debug log for the bootstrap so we can figure on what's going on there...

**Comment by malcook** [comment]
@boegel - hi - it took me a day to get back to this.... Thanks for your help.

As recommended, I am now using Lmod 5.8.5.

My issue remains.

Using your recipe with my addition (of first calling `module load lmod`) fails with same error.

Here is the requested gist with print_debug having been set to True: https://gist.github.com/malcook/8829c325a6a4a8846489

**Comment by malcook** [comment]
I am past this problem and believe the solution was to install tcl.
