### ISSUE TITLE
eb --confighelp contains wrong options in [job] section

### ISSUE THREAD

**Issue by moschlar** [hpcugent/easybuild-framework#1331]
When I uncomment the option ``job-backend-config`` in the ``[job]`` section, I only get the following error message:
```
ERROR: Failed to parse configuration options: parseconfigfiles: no option corresponding with opt job-backend-config dest job_job_backend_config in section job
```
It seems that the section title automatically gets prepended to the option name, so when I strip the ``job-`` prefix from the option name, it works as expected.

**Comment by boegel** [comment]
Thanks for the bug report. This looks like a option with the option parser used by EasyBuild.

cc @stdweird this looks like a bug in generaloption?

**Comment by boegel** [comment]
requires that https://github.com/hpcugent/vsc-base/issues/211 is fixed

**Comment by Flamefire** [comment]
I dug a bit and found a couple of design issues here. The major one blocking this is the following:
- `EasyBuildOptions` (class `GeneralOption`) contains OptionGroups and a parser
- The prefix is incorporated into the Option added to the OptionGroup, which the parser uses
- Parsing the config file(s) is done by `GeneralOption` with something I'd call a "hack" to provide support for prefixes which then yields full options that are then passed to the cmdline parser
- The `confighelp` is implemented at the parser level (in the parser)

So in summary: The parser which does not know anything about config files is responsible for generating the config file.
The parser doesn't even know, how to construct a prefixed option, even less how to decompose one.

--> I'd suggest some reengineering to put the `--confighelp` into the `GeneralOption` and maybe also some refactoring how those are handled. There are some places, where dicts would be much more useful, and another where a `NamedTuple` would be due (see `PROCESSED_OPTIONS_PROPERTIES`)

And maybe `GeneralOption` could be renamed too, I found it confusing while checking the code because it is not "1 option" but a container and handler of all options, parsers, config files etc.

**Comment by sassy-crick** [comment]
I think that problem still persists, as I am getting the same error message. Maybe we should get that fixed in the next release?
